Repository red-velvet-cake-organization/cost-of-living, pull requests merged in 2023-02, with the labels that each got.

#4 Feature/get top fashion cities names
  src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
  src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
Labels: enhancement

#16 Feature/get top fashion cities names
  src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
  src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
Labels: enhancement

#15 feature/get-10-cities-names-to-buy-apartment-faster
  src/main/kotlin/Main.kt
  src/main/kotlin/interactor/GetCitiesNameToBuyApartmentFasterInteractor.kt
  src/test/kotlin/interactor/GetCitiesNameToBuyDepartmentFasterInteractorTest.kt
Labels: enhancement

#20 add additional test cases.
  src/test/kotlin/interactor/GetCitiesNameToBuyDepartmentFasterInteractorTest.kt
Labels: enhancement

#21 Feature/get-10-cities-names-to-buy-apartment-faster-enhancement
  src/main/kotlin/interactor/GetCitiesNameToBuyApartmentFasterInteractor.kt
Labels: bug, enhancement

#24 Feature/get top fashion cities names enhancement
  src/main/kotlin/Main.kt
  src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
  src/test/kotlin/dataSource/FakeDataSource.kt
  src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
Labels: enhancement

#28 feature/add-custom-exceptions
  src/main/kotlin/interactor/exceptions.kt
Labels: enhancement

#33 add new file for extension functions
  src/main/kotlin/utils/extensions.kt
Labels: enhancement

#40 Fix/get top fashion cities names
  src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
  src/main/kotlin/model/ClothesPrices.kt
  src/main/kotlin/utils/Constants.kt
  src/main/kotlin/utils/extensions.kt
  src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
Labels: enhancement

#43 Fix/city match manager expectations
  src/main/kotlin/dataSource/utils/northAmericaCountries.kt
  src/main/kotlin/interactor/GetCityMatchManagerExpectationsInteractor.kt
  src/main/kotlin/utils/Constants.kt
  src/test/kotlin/dataSource/FakeCityItems.kt
  src/test/kotlin/dataSource/FakeEmptyDataSource.kt
  src/test/kotlin/interactor/GetCityMatchManagerExpectationsInteractorTest.kt
Labels: enhancement

#42 Fix/high taxes carbonated drinks
  src/main/kotlin/Main.kt
  src/main/kotlin/interactor/GetTop10CountriesWithHighTaxOnCarbonatedDrinks.kt
  src/main/kotlin/interactor/GetTopCountriesWithHighTaxOnCarbonatedDrinks.kt
  src/test/kotlin/interactor/GetTop10CountriesWithHighTaxOnCarbonatedDrinksTest.kt
  src/test/kotlin/interactor/GetTopCountriesWithHighTaxOnCarbonatedDrinksTest.kt
Labels: enhancement

#46 Fix/get top fashion cities names
  src/main/kotlin/interactor/GetCityMatchManagerExpectationsInteractor.kt
  src/main/kotlin/interactor/GetTopFashionCitiesNamesInteractor.kt
  src/main/kotlin/interactor/exceptions.kt
  src/main/kotlin/utils/Constants.kt
  src/test/kotlin/interactor/GetTopFashionCitiesNamesInteractorTest.kt
Labels: enhancement

#39 Fix/cities names sorted cheapest banana prices
  src/main/kotlin/interactor/GetCitiesNamesSortedCheapestBananaPrices.kt
  src/test/kotlin/interactor/GetCitiesNamesSortedCheapestBananaPricesTest.kt
Labels: enhancement

#52 Fix/get cities names to buy apartment faster
  src/main/kotlin/Main.kt
  src/main/kotlin/interactor/GetCitiesNameToBuyApartmentFasterInteractor.kt
  src/main/kotlin/interactor/GetCityNamesToBuyApartmentFasterInteractor.kt
  src/test/kotlin/interactor/GetCitiesNameToBuyDepartmentFasterInteractorTest.kt
  src/test/kotlin/interactor/GetCityNamesToBuyApartmentFasterInteractorTest.kt
Labels: enhancement

#51 Feature/interact with user enhancement
  src/main/kotlin/Main.kt
  src/main/kotlin/utils/extensions.kt
Labels: enhancement

#62 add un-imported InvalidLimitException class
  src/main/kotlin/interactor/GetTopCountriesWithHighTaxOnCarbonatedDrinks.kt
  src/test/kotlin/interactor/GetCityMatchManagerExpectationsInteractorTest.kt
  src/test/kotlin/interactor/GetCityThatHasLowestCostOfFoodInteractorTest.kt
  src/test/kotlin/interactor/GetLowestAveragePricesForFruitsAndVegetablesInteractorTest.kt
  src/test/kotlin/interactor/GetTopCountriesWithHighTaxOnCarbonatedDrinksTest.kt
Labels: bug
